import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../viewmodels/profile_viewmodel.dart';

class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'English': {
      'Dashboard': 'Dashboard',
      'Profile': 'Profile',
      'Workout': 'Workout',
      'Water': 'Water',
      'Workouts': 'Workouts',
      'My Profile': 'My Profile',
      'Manage your health info': 'Manage your health info',
      'Personal Details': 'Personal Details',
      'Name': 'Name',
      'Age': 'Age',
      'Height': 'Height',
      'Weight': 'Weight',
      'Gender': 'Gender',
      'Fitness Goal': 'Fitness Goal',
      'Language Preference': 'Language Preference',
      'Preferences': 'Preferences',
      'Dark Mode': 'Dark Mode',
      'Account': 'Account',
      'Logout': 'Logout',
      'Welcome': 'Welcome',
      'Daily Progress': 'Daily Progress',
      'Sleep': 'Sleep',
      'Calories': 'Calories',
      'Activity': 'Activity',
      'Good Morning': 'Good Morning',
      'Good Afternoon': 'Good Afternoon',
      'Good Evening': 'Good Evening',
      'Daily Health Tips': 'Daily Health Tips',
      'Quick Stats': 'Quick Stats',
      'Water Goal': 'Water Goal',
      'Sleep Goal': 'Sleep Goal',
      'Calorie Target': 'Calorie Target',
      'Activity Goal': 'Activity Goal',
      'BMI Calculator': 'BMI Calculator',
      'Motivation of the Day': 'Motivation of the Day',
      'Exercise Library': 'Exercise Library',
      'My Logs': 'My Logs',
      'Log Workout': 'Log Workout',
      'Nutrition': 'Nutrition',
      'What is a Healthy Diet?': 'What is a Healthy Diet?',
      'Daily Macro Guide': 'Daily Macro Guide',
      'Top 10 Superfoods': 'Top 10 Superfoods',
      'My Meal Logs': 'My Meal Logs',
      'Log Meal': 'Log Meal',
      'Hydration': 'Hydration',
      "Today's Intake": "Today's Intake",
      'How Water Helps Your Body': 'How Water Helps Your Body',
      'Set Daily Goal': 'Set Daily Goal',
      'Sleep Tracker': 'Sleep Tracker',
      "Last Night's Sleep": "Last Night's Sleep",
      'Sleep Stages': 'Sleep Stages',
      'My Sleep Logs': 'My Sleep Logs',
      'Log Sleep': 'Log Sleep',
      'This Week\'s Sleep': 'This Week\'s Sleep',
      'Why Sleep is Crucial': 'Why Sleep is Crucial',
      'Sleep Cycle Stages': 'Sleep Cycle Stages',
      'Sleep Log': 'Sleep Log',
      'Log Your Sleep': 'Log Your Sleep',
      'Home Workouts Work!': 'Home Workouts Work!',
    },
    'Telugu': {
      'Dashboard': 'డ్యాష్‌బోర్డ్',
      'Profile': 'ప్రొఫైల్',
      'Workout': 'వ్యాయామం',
      'Water': 'నీరు',
      'Workouts': 'వ్యాయామాలు',
      'My Profile': 'నా ప్రొఫైల్',
      'Manage your health info': 'మీ ఆరోగ్య సమాచారాన్ని నిర్వహించండి',
      'Personal Details': 'వ్యక్తిగత వివరాలు',
      'Name': 'పేరు',
      'Age': 'వయస్సు',
      'Height': 'ఎత్తు',
      'Weight': 'బరువు',
      'Gender': 'లింగం',
      'Fitness Goal': 'ఆరోగ్య లక్ష్యం',
      'Language Preference': 'భాషా అనుకూలత',
      'Preferences': 'ప్రాధాన్యతలు',
      'Dark Mode': 'డార్క్ మోడ్',
      'Account': 'ఖాతా',
      'Logout': 'లాగ్అవుట్',
      'Welcome': 'స్వాగతం',
      'Daily Progress': 'రోజువారీ పురోగతి',
      'Sleep': 'నిద్ర',
      'Calories': 'కేలరీలు',
      'Activity': 'కార్యాచరణ',
      'Good Morning': 'శుభోదయం',
      'Good Afternoon': 'శుభ మధ్యాహ్నం',
      'Good Evening': 'శుభ సాయంత్రం',
      'Daily Health Tips': 'రోజువారీ ఆరోగ్య చిట్కాలు',
      'Quick Stats': 'త్వరిత గణాంకాలు',
      'Water Goal': 'నీటి లక్ష్యం',
      'Sleep Goal': 'నిద్ర లక్ష్యం',
      'Calorie Target': 'క్యాలరీ లక్ష్యం',
      'Activity Goal': 'కార్యాచరణ లక్ష్యం',
      'BMI Calculator': 'BMI కాలిక్యులేటర్',
      'Motivation of the Day': 'ఈనాటి సంకల్పం',
      'Exercise Library': 'వ్యాయామం లైబ్రరీ',
      'My Logs': 'నా లాగ్స్',
      'Log Workout': 'వర్కౌట్‌ యాడ్ చేయండి',
      'Nutrition': 'పోషణ',
      'What is a Healthy Diet?': 'ఆరోగ్యకరమైన ఆహారం ఏమిటి?',
      'Daily Macro Guide': 'రోజువారీ మాక్రో గైడ్',
      'Top 10 Superfoods': 'ఉత్తమ 10 ఆదర్శ ఆహారాలు',
      'My Meal Logs': 'నా భోజనం లాగ్స్',
      'Log Meal': 'భోజనాన్ని లాగ్ చేయండి',
      'Hydration': 'హైడ్రేషన్',
      "Today's Intake": 'కొత్త నీరు',
      'How Water Helps Your Body': 'నీరు శరీరానికి ఎలా సహాయపడుతుంది',
      'Set Daily Goal': 'రోజువారీ లక్ష్యం',
      'Sleep Tracker': 'స్లీప్ ట్రాకర్',
      "Last Night's Sleep": 'ગત రాత్రి నిద్ర',
      'Sleep Stages': 'నిద్ర దశలు',
      'My Sleep Logs': 'నా నిద్ర లాగ్స్',
      'Log Sleep': 'స్లీప్ లాగ్ చేయండి',
      'This Week\'s Sleep': 'ఈ వారం నిద్ర',
      'Why Sleep is Crucial': 'నిద్ర ఎందుకు ముఖ్యం',
      'Sleep Cycle Stages': 'నిద్ర చక్రం దశలు',
      'Sleep Log': 'నిద్ర లాగ్',
      'Log Your Sleep': 'మీ నిద్ర లాగ్ చేయండి',
      'Home Workouts Work!': 'ఇంటి వ్యాయామాలు ఉత్తమం!',
    },
    'Hindi': {
      'Dashboard': 'डैशबोर्ड',
      'Profile': 'प्रोफ़ाइल',
      'Workout': 'कसरत',
      'Water': 'पानी',
      'Workouts': 'कार्य',
      'My Profile': 'मेरी प्रोफ़ाइल',
      'Manage your health info': 'अपनी स्वास्थ्य जानकारी प्रबंधित करें',
      'Personal Details': 'व्यक्तिगत विवरण',
      'Name': 'नाम',
      'Age': 'आयु',
      'Height': 'ऊँचाई',
      'Weight': 'वजन',
      'Gender': 'लिंग',
      'Fitness Goal': 'फ़िटनेस लक्ष्य',
      'Language Preference': 'भाषा की पसंद',
      'Preferences': 'प्राथमिकताएं',
      'Dark Mode': 'डार्क मोड',
      'Account': 'खाता',
      'Logout': 'लॉग आउट',
      'Welcome': 'स्वागत है',
      'Daily Progress': 'दैनिक प्रगति',
      'Sleep': 'नींद',
      'Calories': 'कैलोरी',
      'Activity': 'गतिविधि',
      'Good Morning': 'सुप्रभात',
      'Good Afternoon': 'शुभ दोपहर',
      'Good Evening': 'शुभ संध्या',
      'Daily Health Tips': 'दैनिक स्वास्थ्य सुझाव',
      'Quick Stats': 'त्वरित आँकड़े',
      'Water Goal': 'पानी का लक्ष्य',
      'Sleep Goal': 'नींद का लक्ष्य',
      'Calorie Target': 'कैलोरी लक्ष्य',
      'Activity Goal': 'गतिविधि लक्ष्य',
      'BMI Calculator': 'बीएमआई कैलकुलेटर',
      'Motivation of the Day': 'आज की प्रेरणा',
      'Exercise Library': 'व्यायाम पुस्तकालय',
      'My Logs': 'मेरे लॉग',
      'Log Workout': 'कसरत दर्ज करें',
      'Nutrition': 'पोषण',
      'What is a Healthy Diet?': 'स्वस्थ आहार क्या है?',
      'Daily Macro Guide': 'दैनिक मैक्रो गाइड',
      'Top 10 Superfoods': 'शीर्ष 10 सुपरफूड्स',
      'My Meal Logs': 'मेरा भोजन लॉग',
      'Log Meal': 'लॉग भोजन',
      'Hydration': 'जल-योजन',
      "Today's Intake": 'आज का सेवन',
      'How Water Helps Your Body': 'पानी शरीर में कैसे मदद करता है',
      'Set Daily Goal': 'दैनिक लक्ष्य निर्धारित करें',
      'Sleep Tracker': 'स्लीप ट्रैकर',
      "Last Night's Sleep": 'कल रात की नींद',
      'Sleep Stages': 'नींद के चरण',
      'My Sleep Logs': 'मेरे स्लीप लॉग्स',
      'Log Sleep': 'लॉग स्लीप',
      'This Week\'s Sleep': 'इस सप्ताह की नींद',
      'Why Sleep is Crucial': 'नींद क्यों महत्वपूर्ण है',
      'Sleep Cycle Stages': 'नींद के चक्र के चरण',
      'Sleep Log': 'नींद लॉग',
      'Log Your Sleep': 'अपनी नींद दर्ज करें',
      'Home Workouts Work!': 'घरेलू कसरत प्रभावी हैं!',
    }
  };

  static String translate(String key, String language) {
     return _localizedValues[language]?[key] ?? key;
  }
}

extension LocalizationHelper on String {
  String tr(BuildContext context) {
    try {
      final lang = Provider.of<ProfileViewModel>(context, listen: true).language;
      return AppLocalizations.translate(this, lang);
    } catch (_) {
      return this;
    }
  }
}
