// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ0fW3sOIkRjCAmu6hj-x75bqqOUKI4V0',
    appId: '1:135744322932:web:137f7ade7767a6b0f3c021',
    messagingSenderId: '135744322932',
    projectId: 'wellnesspro-90317',
    authDomain: 'wellnesspro-90317.firebaseapp.com',
    storageBucket: 'wellnesspro-90317.firebasestorage.app',
    measurementId: 'G-18F749J3XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV1lheJBfproXaxnMEun_TDr_HFLZdtWQ',
    appId: '1:135744322932:android:bcfa395b74a3706bf3c021',
    messagingSenderId: '135744322932',
    projectId: 'wellnesspro-90317',
    storageBucket: 'wellnesspro-90317.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmyxD-V3ZfLbFtoMcxF3IBBo8EUhKgBGI',
    appId: '1:135744322932:ios:8076022ff8099b73f3c021',
    messagingSenderId: '135744322932',
    projectId: 'wellnesspro-90317',
    storageBucket: 'wellnesspro-90317.firebasestorage.app',
    iosBundleId: 'com.example.fitlife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmyxD-V3ZfLbFtoMcxF3IBBo8EUhKgBGI',
    appId: '1:135744322932:ios:8076022ff8099b73f3c021',
    messagingSenderId: '135744322932',
    projectId: 'wellnesspro-90317',
    storageBucket: 'wellnesspro-90317.firebasestorage.app',
    iosBundleId: 'com.example.fitlife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ0fW3sOIkRjCAmu6hj-x75bqqOUKI4V0',
    appId: '1:135744322932:web:7637fa76e316732df3c021',
    messagingSenderId: '135744322932',
    projectId: 'wellnesspro-90317',
    authDomain: 'wellnesspro-90317.firebaseapp.com',
    storageBucket: 'wellnesspro-90317.firebasestorage.app',
    measurementId: 'G-3LKTTBPZ7D',
  );
}
